### ISSUE TITLE
Hello, I am getting this error while running the program. 

### ISSUE THREAD

**Issue by AmeyHengle** [YaboLee/reddit_crawler#1]
Start to collect all submission ids...

Traceback (most recent call last):

  File "C:/Users/Amey/PycharmProjects/Reddit_Text_Analysis/reddit_crawlier.py", line 127, in <module>
    c.save_comments_submissions(pages)
  File "C:/Users/Amey/PycharmProjects/Reddit_Text_Analysis/reddit_crawlier.py", line 93, in save_comments_submissions
    self.get_submission_ids(pages)
  File "C:/Users/Amey/PycharmProjects/Reddit_Text_Analysis/reddit_crawlier.py", line 54, in get_submission_ids
    after = ids[-1]

IndexError: list index out of range

**Comment by jellyfish45** [comment]
I have the same problem too...It seems that my code didn't get anything from the website so the ids is blank
